In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
print(tf.__version__)

2.3.0


In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
!ls

Churn_Modelling.csv  sample_data


In [5]:
dataset = pd.read_csv('data/Churn_Modelling.csv')

In [6]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [8]:
X = dataset.drop(labels=['RowNumber', 'CustomerId', 'Surname', 'Exited'], axis=1)
y = dataset['Exited']

In [9]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [10]:
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
label1 = LabelEncoder()
X['Geography'] = label1.fit_transform(X['Geography'])

In [13]:
X.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [14]:
label1.classes_

array(['France', 'Germany', 'Spain'], dtype=object)

In [15]:
label2 = LabelEncoder()
X['Gender'] = label2.fit_transform(X['Gender'])
X.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [16]:
X = pd.get_dummies(X, drop_first=True, columns=['Geography'])
X.head()

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1

[5 rows x 11 columns]

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)

In [19]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [20]:
x_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

In [21]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(X.shape[1], activation = 'relu', input_dim = X.shape[1]))
model.add(keras.layers.Dense(128, activation='relu'))
model.add(keras.layers.Dense(1, activation='sigmoid'))

In [22]:
X.shape

(10000, 11)

In [23]:
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

In [24]:
model.fit(x_train, y_train.to_numpy(), batch_size= 10, epochs=10, verbose=1)

Epoch 1/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4455 - accuracy: 0.8077
Epoch 2/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4021 - accuracy: 0.8317
Epoch 3/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3775 - accuracy: 0.8422
Epoch 4/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3600 - accuracy: 0.8485
Epoch 5/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3492 - accuracy: 0.8537
Epoch 6/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3438 - accuracy: 0.8576
Epoch 7/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3419 - accuracy: 0.8576
Epoch 8/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3376 - accuracy: 0.8601
Epoch 9/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3354 - accuracy: 0.8629
Epoch 10/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3350 - accuracy: 0.8600

In [25]:
y_pred = model.predict_classes(x_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [26]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int32)

In [27]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [28]:
model.evaluate(x_test, y_test.to_numpy())

63/63 [==============================] - 0s 2ms/step - loss: 0.3572 - accuracy: 0.8555


[0.35724663734436035, 0.8554999828338623]

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [30]:
confusion_matrix(y_test, y_pred)

array([[1545,   48],
       [ 241,  166]])

In [31]:
accuracy_score(y_test, y_pred)

0.8555