[View in Colaboratory](https://colab.research.google.com/github/partha1189/ml/blob/master/numpy1.ipynb)

In [1]:
my_list = [1,2,3,4]
import numpy as np
arr = np.array(my_list)
print(arr)

[1 2 3 4]


In [2]:
help(np.arange)


Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

In [3]:
np.arange(4,13,2)

array([ 4,  6,  8, 10, 12])

In [4]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.random.rand(2,2)

array([[0.59185295, 0.02958281],
       [0.15097547, 0.77232064]])

In [8]:
np.random.randn(5)

array([ 0.86148432, -0.04098502,  0.0111561 , -0.34287288,  0.69055223])